spring:
  profiles:
    active: dev
    
server:
  port: 8080
  servlet:
    contextPath: /coding
    
    
app:
  datasources:
    restDatasources[0]: https://opentdb.com/api.php?amount=5&category=11
    #restDatasources[1]: https://opentdb.com/api.php?amount=5&category=12


logging:
  level:
    root: DEBUG
  